name: player_hls
description: A new Flutter package project.
version: 0.0.1
author: ""
homepage: "https://github.com"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  helpers: ^1.0.3
  flutter_vlc_player: ^5.0.2
  mobx: 1.2.1+1
  flutter_mobx: ^1.1.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.11.1

flutter:
